### ISSUE TITLE
Editer le titre d'une recette casse les URLs

### ISSUE THREAD

**Issue by phito** [micbelgique/MICCookBook#3]
Le fait de valider les slugs pour les recettes fait que si l'on modifie le titre d'une recette, les anciennes URLs pointant vers cette recette ne fonctionneront plus.

**Comment by mrrenaud** [comment]
Exact, c'est embêtant. Tu suggères quoi ?

Une solution pourrait être, à l'édition d'une recette, d'afficher l'url actuelle dans un champs en précisant à l'utilisateur qu'il est possible de la modifier/corriger, mais que les anciens liens ne fonctionneront plus.

**Comment by phito** [comment]
En général les sites ne vérifient juste pas le slug, juste l'ID contenu dans l'url.

### Exemple:

https://www.reddit.com/r/programming/comments/5us48z/evilpass_slightly_evil_password_strength_checker
et
https://www.reddit.com/r/programming/comments/5us48z/is_the_slug_checked_or_not

redirigent tout les deux vers la même page (il y a l'air tout de même d'avoir une sorte de redirection pour corriger le slug).

**Comment by mrrenaud** [comment]
Ouais en effet, le problème c'est que avoir le même contenu accessible par plusieurs adresses, ce n'est pas une bonne idée niveau SEO. C'est comme si on avait du contenu dupliqué.

Eventbrite aussi fait une redirection : 
[https://www.eventbrite.fr/e/billets-visual-studio-2017-launch-event-31994426190](https://www.eventbrite.fr/e/billets-visual-studio-2017-launch-event-31994426190)
[https://www.eventbrite.fr/e/billets-blablabla-event-31994426190](https://www.eventbrite.fr/e/billets-blablabla-event-31994426190)

Du coup la redirection 301 me semble être une solution élégante 👍

**Comment by mrrenaud** [comment]
Fixed ! http://miccookbook.azurewebsites.net/recipes/details/1/cheesy-thanks!
